# Generated by Django 3.0.5 on 2020-12-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehub', '0005_auto_20201125_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=300)),
                ('productdetails', models.TextField()),
                ('productprize', models.FloatField()),
                ('productimage', models.ImageField(null=True, upload_to='')),
                ('productcategory', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
